# Generated by Django 4.2.2 on 2023-06-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusquedaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_busqueda', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='dni',
            new_name='cedula',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='domicilio',
            new_name='direccion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_de_alta',
        ),
    ]
